/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module 'sst' {
  export interface Resource {
    dev_daily_hub: {
      type: 'sst.aws.Astro'
      url: string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst'
export {}
