export const getBlogPostPaths = () => {
  return [
    {
      path: 'how-to-pass-ielts',
      indTitle: 'Bagaimana cara lulus Ujian IELTS',
      title: 'How to pass the IELTS Exam',
      size: { colSpan: '2', rowSpan: '1' },
      indTags: ['pendidikan', 'visa', 'Inggris visa'],
      tags: ['education', 'visa', 'UK visa'],
      new: true,
      published: '2022/06/08',
    },
    {
      path: 'obtaining-a-family-visa',
      indTitle: 'Cara mendapatkan visa keluarga Inggris',
      title: 'How to get a UK family visa',
      size: { colSpan: '1', rowSpan: '1' },
      indTags: ['visa', 'Inggris visa'],
      tags: ['visa', 'UK visa'],
      new: true,
      published: '2022/06/12',
    },
    {
      path: 'what-to-do-in-indonesia',
      indTitle: 'panduan perjalanan Indonesia',
      title: 'Indonesia travel guide',
      size: { colSpan: '1', rowSpan: '1' },
      indTags: ['bepergian', 'indonesia'],
      tags: ['travel', 'indonesia'],
      new: true,
      published: '2022/07/15',
    },
    {
      path: 'what-to-do-in-jogja',
      indTitle: 'Cara menghabiskan waktu di Jogja',
      title: 'How to spend your time in Jogja',
      size: { colSpan: '1', rowSpan: '1' },
      indTags: ['bepergian', 'indonesia'],
      tags: ['travel', 'indonesia'],
      new: true,
      published: '2022/07/17',
    },
    {
      path: 'marriage-requirements',
      indTitle: 'Panduan Pernikahan WNA dengan WNI di Indonesia',
      title:
        'Guide for Marriage between a foreigner and Indonesian citizen in Indonesia',
      size: { colSpan: '1', rowSpan: '1' },
      indTags: ['pernikahan', 'cinta'],
      tags: ['marriage', 'love'],
      new: true,
      published: '2022/07/20',
    },
    {
      path: 'best-uk-theme-parks',
      indTitle: 'Taman hiburan uk terbaik',
      title: 'Best UK Theme Parks',
      size: { colSpan: '1', rowSpan: '1' },
      indTags: ['UK', 'bepergian'],
      tags: ['UK', 'thrill', 'roller coasters', 'coasters', 'days out'],
      new: true,
      published: '2022/08/15',
    },
    {
      path: 'alton-towers',
      indTitle: 'Alton Towers',
      title: 'Things to know about Alton Towers',
      size: { colSpan: '2', rowSpan: '1' },
      indTags: ['UK', 'bepergian'],
      tags: ['UK', 'thrill', 'roller coasters', 'coasters', 'days out'],
      new: true,
      published: 'N/A',
    },
  ];
};
