import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Box } from '@chakra-ui/react';
import HomeBackground from '../components/HomeBackground';
import HomeHeader from '../components/HomeHeader';

export default function Home() {
  return (
    <Box w="100%" h="100%">
      <Head>
        <title>Double A Team</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      
      <main className={styles.main}>
        <HomeBackground />
        <HomeHeader />
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </Box>
  );
}
